### ISSUE TITLE
New bug, when i use mysql. I not have any error on join/quit. But i have this new:

### ISSUE THREAD

**Issue by Ethon6** [Rosstail/Nodewar#2]
![image](https://user-images.githubusercontent.com/19668243/152969914-fbf1c0fa-d747-42bd-958a-97b8e16f7ab6.png)

`[11:32:32] [Server thread/WARN]: [Nodewar] Task #2192 for Nodewar v1.2.0 generated an exception
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "fr.rosstail.nodewar.territory.zonehandlers.Territory.getRegion()" is null
        at fr.rosstail.nodewar.territory.eventhandlers.worldguardevents.RegionLeftEvent.lambda$new$1(RegionLeftEvent.java:28) ~[?:?]
        at java.util.HashMap.forEach(HashMap.java:1420) ~[?:?]
        at fr.rosstail.nodewar.territory.eventhandlers.worldguardevents.RegionLeftEvent.<init>(RegionLeftEvent.java:27) ~[?:?]
        at fr.rosstail.nodewar.territory.eventhandlers.WGRegionEventsListener$2.run(WGRegionEventsListener.java:156) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3427-Spigot-6edb62f-de95135]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3427-Spigot-6edb62f-de95135]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1255) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3427-Spigot-6edb62f-de95135]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:428) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3427-Spigot-6edb62f-de95135]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3427-Spigot-6edb62f-de95135]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3427-Spigot-6edb62f-de95135]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3427-Spigot-6edb62f-de95135]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[11:33:08] [Craft Scheduler Thread - 7/INFO]: [VoidGen] Update v2.2.1 is available: null`

**Comment by Rosstail** [comment]
It is not a new bug but it's the one remaining when you enable sql, it may have something with territories files, I'll check it.
